In [ ]:
Assignment Questions
1.Using Numpy to generate an array of 25 random numbers sampled from a standard normal distribution




In [1]:
import numpy as np
np.random.rand(25)

array([0.58860571, 0.3344059 , 0.60384991, 0.41739651, 0.64024209,
       0.29906682, 0.89710573, 0.33823524, 0.33586489, 0.92384035,
       0.91241574, 0.61430181, 0.22044672, 0.85548583, 0.30625048,
       0.09957226, 0.30881371, 0.79021528, 0.56605074, 0.08614554,
       0.23786283, 0.34010418, 0.93342524, 0.22421319, 0.9888146 ])

In [ ]:
2.Create an array of 20 linear spaced points between 0 and 1

In [2]:

np.linspace(0, 1, 20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
3.Declare a numpy array of values from 1 to 100 and make it into 10*10 matrix


In [3]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
4.Using the previously defind matrix print rows 1,5,6

In [4]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [ ]:
5.Using the previously defined matrix print elements from 3rd row to 10th row

In [5]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
6.Using the previously defined matrix print all the elements from 4th row to 8th row

In [6]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


In [ ]:
7.Using the same matrix print values from 3rd row 2nd column to 5th row 8th column

In [7]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [ ]:
8.Write a code to generate random 1000 numbers each in range (0,1) such that the count of all random points like are almost same

In [8]:
np.random.rand(100)

array([0.59203869, 0.56018999, 0.2387047 , 0.47477586, 0.09477584,
       0.7356867 , 0.83956472, 0.7639554 , 0.2466809 , 0.70774126,
       0.70655223, 0.2052447 , 0.84169575, 0.74450028, 0.57966822,
       0.07778399, 0.70941438, 0.84608134, 0.06684646, 0.14755058,
       0.79305751, 0.07448204, 0.21910255, 0.31373628, 0.18816867,
       0.94758929, 0.00608234, 0.60904878, 0.49978196, 0.73666763,
       0.8723173 , 0.08448017, 0.04939194, 0.6391175 , 0.49989335,
       0.72981962, 0.42626181, 0.78607356, 0.14009981, 0.98884341,
       0.67918962, 0.04957588, 0.11464618, 0.59338477, 0.3215545 ,
       0.23400575, 0.56025927, 0.08319531, 0.94944618, 0.87605143,
       0.26374732, 0.81776243, 0.22946711, 0.50233479, 0.20114177,
       0.55622485, 0.26282021, 0.54790831, 0.28266449, 0.93443218,
       0.38367396, 0.18866211, 0.69769286, 0.50476153, 0.99025556,
       0.83422959, 0.88055496, 0.6446636 , 0.00377769, 0.29104076,
       0.57818361, 0.30454649, 0.26783957, 0.55305205, 0.06090

In [ ]:
9.Write the commands to get standard deviation, mean,median,mode for a given vector

In [9]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [10]:
np.median(a)

4.5

In [11]:
np.std(a)

1.8027756377319946

In [12]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [13]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))